package com.civicai.citizen.voice;

public enum ConversationState {
    IDLE,
    COLLECTING_CATEGORY,
    CONFIRMING_CATEGORY,
    COLLECTING_LOCATION,
    CONFIRMING_LOCATION,
    COLLECTING_DESCRIPTION,
    CONFIRMING_DESCRIPTION,
    COLLECTING_TITLE,
    CONFIRMING_TITLE,
    FINAL_REVIEW,
    SUBMITTED,
    ERROR
}
